# -*- coding: utf-8 -*-
"""Page View Time Series Visualizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17EszSMcbvC384qKRwLTFmdub7ZscIdiy
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.tsa.arima.model import ARIMA

# %matplotlib inline

# ---------- LOAD & CLEAN DATA ----------
df = pd.read_csv("fcc-forum-pageviews.csv", parse_dates=['date'], index_col='date')

# Remove top 2.5% and bottom 2.5%
df = df[(df['value'] >= df['value'].quantile(0.025)) &
        (df['value'] <= df['value'].quantile(0.975))]

# ---------- 3. LINE PLOTS ----------
def draw_line_plot():
    fig, ax = plt.subplots(figsize=(12,5))
    ax.plot(df.index, df['value'], color="red")

    ax.set_title("Daily freeCodeCamp Forum Page Views 5/2016–12/2019")
    ax.set_xlabel("Date")
    ax.set_ylabel("Page Views")

    plt.show()
    fig.savefig("line_plot.png")

draw_line_plot()

# ---------- 3. BAR PLOTS ----------
def draw_bar_plot():
    df_bar = df.copy()
    df_bar['year'] = df_bar.index.year
    df_bar['month'] = df_bar.index.strftime('%B')

    df_grouped = df_bar.groupby(['year', 'month'])['value'].mean().unstack()

    fig = df_grouped.plot(kind='bar', figsize=(12,6)).figure
    plt.xlabel("Years")
    plt.ylabel("Average Page Views")
    plt.legend(title="Months")

    plt.show()
    fig.savefig("bar_plot.png")

draw_bar_plot()

def draw_box_plot():
    df_box = df.copy()
    df_box['year'] = df_box.index.year
    df_box['month'] = df_box.index.strftime('%b')
    df_box['month_num'] = df_box.index.month
    df_box = df_box.sort_values('month_num')

    fig, axes = plt.subplots(1, 2, figsize=(15,7))

    sns.boxplot(x='year', y='value', data=df_box, ax=axes[0])
    axes[0].set_title("Year-wise Box Plot (Trend)")
    axes[0].set_xlabel("Year")
    axes[0].set_ylabel("Page Views")

    sns.boxplot(x='month', y='value', data=df_box, ax=axes[1])
    axes[1].set_title("Month-wise Box Plot (Seasonality)")
    axes[1].set_xlabel("Month")
    axes[1].set_ylabel("Page Views")

    plt.show()
    fig.savefig("box_plot.png")

draw_box_plot()

# ---------- 4. MOVING AVERAGES ----------
def draw_moving_average():
    df_ma = df.copy()
    df_ma['7-day MA'] = df_ma['value'].rolling(7).mean()
    df_ma['30-day MA'] = df_ma['value'].rolling(30).mean()

    fig, ax = plt.subplots(figsize=(12,5))
    ax.plot(df_ma['value'], label="Original")
    ax.plot(df_ma['7-day MA'], label="7-day Moving Avg")
    ax.plot(df_ma['30-day MA'], label="30-day Moving Avg")

    plt.legend()
    plt.title("Moving Average Analysis")
    plt.xlabel("Date")
    plt.ylabel("Page Views")

    plt.show()
    fig.savefig("moving_average.png")

draw_moving_average()

# ---------- 5. DECOMPOSITION ----------
def draw_decomposition():
    decomposition = seasonal_decompose(df['value'], model='additive', period=30)

    fig = decomposition.plot()
    fig.set_size_inches(12, 10)

    plt.show()
    fig.savefig("decomposition.png")

draw_decomposition()

# ---------- 6. ANOMALY DETECTION ----------
def draw_anomalies():
    df_anom = df.copy()
    mean = df_anom['value'].mean()
    std = df_anom['value'].std()
    df_anom['z_score'] = (df_anom['value'] - mean) / std

    anomalies = df_anom[df_anom['z_score'].abs() > 3]

    fig, ax = plt.subplots(figsize=(12,5))
    ax.plot(df_anom['value'], label="Page Views")
    ax.scatter(anomalies.index, anomalies['value'], color='red', label="Anomalies")

    plt.legend()
    plt.title("Anomaly Detection")
    plt.xlabel("Date")
    plt.ylabel("Page Views")

    plt.show()
    fig.savefig("anomalies.png")

draw_anomalies()

# ARIMA Forecasting cell (replace previous draw_forecast or add as new cell)
from statsmodels.tsa.arima.model import ARIMA
import pandas as pd
import matplotlib.pyplot as plt

def draw_forecast_and_save(df, steps=180):
    # Fit ARIMA; adjust order if needed after experimentation
    model = ARIMA(df['value'], order=(5,1,2))
    model_fit = model.fit()

    # Get forecast with confidence intervals
    fc = model_fit.get_forecast(steps=steps)
    fc_df = fc.summary_frame(alpha=0.05)  # columns: mean, mean_se, mean_ci_lower, mean_ci_upper

    # fc_df index will be the next steps' datetimes if the index is a DatetimeIndex
    # Plot historical + forecast + CI
    fig, ax = plt.subplots(figsize=(12,5))
    ax.plot(df.index, df['value'], label='Historical')
    ax.plot(fc_df.index, fc_df['mean'], label='Forecast', color='green')
    ax.fill_between(fc_df.index, fc_df['mean_ci_lower'], fc_df['mean_ci_upper'],
                    color='k', alpha=0.15, label='95% CI')
    ax.set_title(f'{steps}-day Forecast using ARIMA')
    ax.set_xlabel('Date')
    ax.set_ylabel('Page Views')
    ax.legend()
    plt.show()
    fig.savefig("forecast_with_ci.png")

    # Print top rows and save numeric values
    print("Forecast (first 10 rows):")
    display(fc_df.head(10))   # in Colab this will show a nice table

    # Save to csv
    fc_df.to_csv("forecast_values.csv")
    print("Saved forecast values to forecast_values.csv")

    return fc_df

# call it (after df is defined)
forecast_table = draw_forecast_and_save(df, steps=180)